# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

brute_force <- function(xPoints_mat, k, param_prefixes, solver_dir, log_dir) {
    .Call('deepbayes_brute_force', PACKAGE = 'deepbayes', xPoints_mat, k, param_prefixes, solver_dir, log_dir)
}

max_iter_optimize <- function(xPoints_mat, k, budget, solver_dir, log_dir) {
    .Call('deepbayes_max_iter_optimize', PACKAGE = 'deepbayes', xPoints_mat, k, budget, solver_dir, log_dir)
}

max_iter_brute_force <- function(xPoints_mat, k, solver_dir, log_dir) {
    invisible(.Call('deepbayes_max_iter_brute_force', PACKAGE = 'deepbayes', xPoints_mat, k, solver_dir, log_dir))
}

num_node_optimize <- function(xPoints_mat, k, budget, solver_dir, log_dir) {
    .Call('deepbayes_num_node_optimize', PACKAGE = 'deepbayes', xPoints_mat, k, budget, solver_dir, log_dir)
}

num_node_brute_force <- function(xPoints_mat, k, solver_dir, log_dir) {
    invisible(.Call('deepbayes_num_node_brute_force', PACKAGE = 'deepbayes', xPoints_mat, k, solver_dir, log_dir))
}

optimize <- function(xPoints_mat, k, budget, param_prefixes, solver_dir, log_dir) {
    .Call('deepbayes_optimize', PACKAGE = 'deepbayes', xPoints_mat, k, budget, param_prefixes, solver_dir, log_dir)
}

setup <- function(dir) {
    invisible(.Call('deepbayes_setup', PACKAGE = 'deepbayes', dir))
}

